name: highcharts4dart
version: 0.1.0+6
author: Gonzalo Pezzi <gonzalopezzi@gmail.com>
description: Highcharts component for Angular Dart
homepage: https://github.com/gonzalopezzi/highcharts4dart
environment:
  sdk: '>=1.4.2'
dependencies:
  angular: ">=1.0.0 <2.0.0"
  browser: any
  js: any
  observe: '>=0.8.10+4 <0.12.0'
transformers:
  - angular
